### ISSUE TITLE
setup.py install_requires causing dependency issues

### ISSUE THREAD

**Issue by opsyne** [terminal-labs/lektor-jinja-content#15]
Over at <https://gitlab.torproject.org/tpo/onion-services/onion-launchpad/-/merge_requests/48> we ran into some strange dependency problems in our CI build, and eventually tracked it down to to this line:

https://github.com/terminal-labs/lektor-jinja-content/blob/ca530871a6b1b7c1df768293839bc7992d92bbb8/setup.py#L36

We found that this install_requires line was causing a newer version of lektor to be installed than we specified, and at least one of our plugins just wasn't installed.

None of our other plugins have this install_requires, so I assume it wouldn't cause any issues to remove it.

**Comment by nixjdm** [comment]
You are correct! This should be removed. I'll pull and publish a new version asap. Thanks for the report!

**Comment by opsyne** [comment]
@nixjdm thanks for the quick response!

**Comment by nixjdm** [comment]
On second thought, practically, this line shouldn't be needed, but it is technically correct. Rather, the problem is upstream in Lektor, with this line causing a reinstallation that clobbers the version you need. That will be resolved in due time. https://github.com/lektor/lektor/pull/1065 But, not rushing that, I'll publish a new version of this plugin for now without the line to get you moving. It shouldn't harm much, becasue Lektor _should_ be present anyway.

Out of curiosity, can you tell me which version of Lektor you're trying to use? I'd encourage the effort to update. If you have an issue with the current version, please post an issue over there.

**Comment by opsyne** [comment]
I appreciate the speedy update! We're currently using a fork with that line commented so we're not in any rush if it ends up taking a while.

We're currently using lektor 3.3.6. The newer lektor version wasn't too much of an issue, we were more concerned with not using the hash-pinned version we specified, and also that our plugins were getting clobbered.

**Comment by nixjdm** [comment]
Great, thanks for the feedback!

**Comment by opsyne** [comment]
Sure, thanks for the help!
